import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'


import dbConnect from '../database/dbConnect'
import ProductController from '../database/controllers/product'
import ProductModel from '../database/models/product'

// @ts-ignore
const Home: NextPage = ({ products }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        

          
          { products &&
          // @ts-ignore
          products.products.map(prod => {
            return (
              <div key={prod.name}>
                <p>{prod.name}</p>
                <p>{prod.price}</p>
              </div>
            )
          })}
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

// @ts-ignore
export async function getServerSideProps(context) {
  var products = {}
  try{
    products = await ProductController.getProducts();
  } catch(e){}
  
  return { props: { products: products } }
}

export default Home
