import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'


import dbConnect from '../database/dbConnect'
import {getProducts} from '../database/controllers/product'
import ProductModel from '../database/models/product'

// @ts-ignore
const Home: NextPage = ({ products }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1> Bem vindo ao Ecommerce</h1>

      <main className={styles.main}>
          { products &&
          // @ts-ignore
          products.map(prod => {
            return (
              <div key={prod.id}>
                <p>{prod.id} - {prod.title}</p>
              </div>
            )
          })}
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

// @ts-ignore
export async function getServerSideProps(context) {
  var products = {}
  try{
    //products = await getProducts();

    products = await fetch('https://jsonplaceholder.typicode.com/users/1/albums')
      .then(response => response.json())

  } catch(e){}
  
  return { props: { products: products } }
}

export default Home
